include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - build/**
linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    prefer_const_constructors: false
    prefer_single_quotes: true
    cancel_subscriptions: true
    annotate_overrides: true
    empty_constructor_bodies: true
    require_trailing_commas: true