name: api_lojinha
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  dart_jsonwebtoken: ^2.12.1
  equatable: ^2.0.5
  orm: ^3.4.4
  
  

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  wzap:
    git:
      url: https://LeonardoHM@bitbucket.org/time-w2o/wzap-flutter-package.git
      ref: master
